---
- name: Local IP info
  hosts: tower_demo
  connection: local
  gather_facts: no
  tasks:
    - name: Get my public IP
      ipify_facts:
    - name: show ip
      debug:
        msg: "{{ ipify_public_ip }}"
