---
- name: Connection test
  hosts: tower_demo
  gather_facts: no
  tasks:
    - name: Get my public IP
      community.general.ipify_facts:
    - name: show ip
      debug:
        msg: "{{ ipify_public_ip }}"
